start_position: [1,5,2]
goal_position: [20,5,2]
total_planning_time: 30.0

max_distance: 1
r_rrt: 1
rrg_r: 1.5
epsilon: 0.5

quadrotor_speed: 1
quadrotor_radius: 0.5


collision_threshold: 0.07
planning_time_limit: 60
max_iterations: 50
max_iterations_after_collision_free: 15

learning_rate: 0.1

obstacle_cost_weight: 0.1

dynamic_obstacle_cost_weight: 0.1
dynamic_collision_factor: 0.1

smoothness_cost_weight: 0.1
smoothness_cost_velocity: 0.0
smoothness_cost_acceleration: 1.0
smoothness_cost_jerk: 0.0

ridge_factor: 0.0
min_clearence: 0.5
joint_update_limit: 0.1

discretization: 0.5